# ── AWS Provider ─────────────────────────────────────────────
variable "aws_region" {
  type        = string
  description = "AWS region to deploy resources in"
  default     = "us-east-1"
}

# ── S3 Buckets ──────────────────────────────────────────────
variable "input_bucket_name" {
  type        = string
  description = "Name of the input S3 bucket"
  default     = "linguaflow-input-bucket"
}

variable "responses_bucket_name" {
  type        = string
  description = "Name of the responses S3 bucket"
  default     = "linguaflow-responses-bucket"
}

# ── Application IAM Role ────────────────────────────────────
variable "app_role_name" {
  type        = string
  description = "IAM role name for Lambda/ECS tasks"
  default     = "linguaflow-lambda-role"
}

# ── ECS Container / Cluster ─────────────────────────────────
variable "ecs_image_url" {
  type        = string
  description = "ECR image URL for the ECS container"
  default     = "247226602568.dkr.ecr.us-east-1.amazonaws.com/linguaflow:latest"
}

/*variable "execution_role_arn" {
  type        = string
  description = "IAM role ARN for ECS task execution"
  # You can leave default blank, as it will be generated by your ecs_execution_role module
}*/

variable "subnets" {
  type        = list(string)
  description = "Subnets for ECS tasks"
  default     = [
    "subnet-0233369277e645148",  # us-east-1a
    "subnet-072fc1f71f29b384f"   # us-east-1b
  ]
}

variable "vpc_id" {
  type        = string
  description = "VPC ID where ECS will run"
  default     = "vpc-035a69cccae29e1c1"
}

variable "container_port" {
  type        = number
  description = "Port the ECS container listens on"
  default     = 80
}

variable "cpu" {
  type        = string
  description = "ECS task CPU units"
  default     = "256"
}

variable "memory" {
  type        = string
  description = "ECS task memory (MB)"
  default     = "512"
}